# Generated by Django 4.2.17 on 2024-12-06 02:10

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_preview_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=app.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])]),
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
